@url=http://localhost:5000
@api=/api/v1
@email=YOUR_EMAIL
@password=YOUR_PASSWORD
@repassword=YOUR_PASSWORD
@id=USER_ID
@nanoLink=NANO_LINK
@originLink=https://www.youtube.com/
@token=TOKEN

### POST LOGIN
POST {{url}}{{api}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### POST REGISTER
POST {{url}}{{api}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "repassword": "{{repassword}}"
}

### GET user info
GET {{url}}{{api}}/auth/protected HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### GET ALL LINKS
GET {{url}}{{api}}/links HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### GET ORIGINLINK BY NANOLINK
GET {{url}}{{api}}/links/{{nanoLink}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### GET LINK BY ID: TRADITIONAL CRUD
GET {{url}}{{api}}/links/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### CREATE LINK
POST {{url}}{{api}}/links HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "originLink": "{{originLink}}"
}

### DELETE LINK
DELETE {{url}}{{api}}/links/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### UPDATE LINK
PATCH  {{url}}{{api}}/links/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "originLink": "{{originLink}}"
}

### GET NANOLINK
GET {{url}}/{{nanoLink}} HTTP/1.1